name: rps_dart_sdk
description: "A modern, production-ready Dart SDK for Remote Printing Service (RPS) with comprehensive offline support, intelligent retry mechanisms, and real-time monitoring."
version: 1.0.0
homepage: https://github.com/yourusername/rps_dart_sdk

environment:
  sdk: ^3.8.1

dependencies:
  # Network
  dio: ^5.9.0

  # Cache Storage
  hive_ce: ^2.11.3

  # Util
  equatable: ^2.0.7
  logger: ^2.6.1

  # Optional dependencies for platform-specific utilities
  # Uncomment the following if you need proper platform directory support:
  # path_provider: ^2.1.1

dev_dependencies:
  test: ^1.25.8
  lints: ^5.0.0
  hive_ce_generator: ^1.9.3
  build_runner: ^2.4.7
